<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $questions = [
            // TOEIC Reading Questions
            [
                'question_text' => 'The marketing department _____ the new advertising campaign next week.',
                'option_a' => 'launch',
                'option_b' => 'launches',
                'option_c' => 'will launch',
                'option_d' => 'launching',
                'correct_answer' => 'C',
                'explanation' => 'Future tense is needed to describe a planned future action.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'Please submit your expense reports _____ the end of each month.',
                'option_a' => 'by',
                'option_b' => 'until',
                'option_c' => 'for',
                'option_d' => 'since',
                'correct_answer' => 'A',
                'explanation' => 'The preposition "by" is used to indicate a deadline.',
                'difficulty_level' => 'easy',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'The company\'s profits have increased _____ 15% compared to last year.',
                'option_a' => 'in',
                'option_b' => 'by',
                'option_c' => 'at',
                'option_d' => 'for',
                'correct_answer' => 'B',
                'explanation' => 'The preposition "by" is used to indicate the amount of change.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'If the weather _____ better, we would have gone to the beach.',
                'option_a' => 'was',
                'option_b' => 'had been',
                'option_c' => 'would be',
                'option_d' => 'were',
                'correct_answer' => 'B',
                'explanation' => 'Third conditional requires "had been" for past unreal situations.',
                'difficulty_level' => 'hard',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // IELTS Reading Questions
            [
                'question_text' => 'According to the passage, what is the main cause of global warming?',
                'option_a' => 'Deforestation',
                'option_b' => 'Greenhouse gas emissions',
                'option_c' => 'Industrial pollution',
                'option_d' => 'Ocean acidification',
                'correct_answer' => 'B',
                'explanation' => 'The passage identifies greenhouse gas emissions as the primary contributor to global warming.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'The author suggests that renewable energy sources:',
                'option_a' => 'are not economically viable',
                'option_b' => 'require significant infrastructure investment',
                'option_c' => 'are the only solution to climate change',
                'option_d' => 'should be combined with other energy sources',
                'correct_answer' => 'D',
                'explanation' => 'The author advocates for a mixed approach to energy production.',
                'difficulty_level' => 'hard',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'What does the term "carbon footprint" refer to?',
                'option_a' => 'The amount of carbon dioxide released by an individual or organization',
                'option_b' => 'The size of a carbon-based organism',
                'option_c' => 'The measurement of carbon in soil',
                'option_d' => 'The carbon content in fossil fuels',
                'correct_answer' => 'A',
                'explanation' => 'Carbon footprint measures the total greenhouse gas emissions caused by an individual or organization.',
                'difficulty_level' => 'easy',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // TOEFL Reading Questions
            [
                'question_text' => 'What can be inferred from the passage about the author\'s view on renewable energy?',
                'option_a' => 'It is too expensive to implement',
                'option_b' => 'It is the only solution to climate change',
                'option_c' => 'It requires more research and development',
                'option_d' => 'It is not effective in reducing carbon emissions',
                'correct_answer' => 'C',
                'explanation' => 'The author suggests that while renewable energy is promising, more research and development is needed.',
                'difficulty_level' => 'hard',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'The passage suggests that early human civilizations:',
                'option_a' => 'were primarily nomadic',
                'option_b' => 'developed agriculture independently',
                'option_c' => 'had advanced technology',
                'option_d' => 'lived in isolation',
                'correct_answer' => 'B',
                'explanation' => 'The passage indicates that agriculture developed independently in different regions.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Business English Questions
            [
                'question_text' => 'Which of the following is the most appropriate way to begin a formal business email?',
                'option_a' => 'Hey there,',
                'option_b' => 'Dear Sir/Madam,',
                'option_c' => 'Hi everyone,',
                'option_d' => 'What\'s up?',
                'correct_answer' => 'B',
                'explanation' => 'In formal business communication, "Dear Sir/Madam," is the most appropriate salutation.',
                'difficulty_level' => 'easy',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'In a business meeting, what does "to table a motion" mean?',
                'option_a' => 'To postpone discussion of a topic',
                'option_b' => 'To present a new idea',
                'option_c' => 'To reject a proposal',
                'option_d' => 'To approve a decision',
                'correct_answer' => 'A',
                'explanation' => 'To table a motion means to postpone or delay discussion of a topic.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // General English Questions
            [
                'question_text' => 'Choose the correct sentence:',
                'option_a' => 'She don\'t like coffee.',
                'option_b' => 'She doesn\'t likes coffee.',
                'option_c' => 'She doesn\'t like coffee.',
                'option_d' => 'She not like coffee.',
                'correct_answer' => 'C',
                'explanation' => 'The correct form uses "doesn\'t" (third person singular) and the base form of the verb.',
                'difficulty_level' => 'easy',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'question_text' => 'Which sentence uses the present perfect tense correctly?',
                'option_a' => 'I have seen that movie yesterday.',
                'option_b' => 'I saw that movie yesterday.',
                'option_c' => 'I have seen that movie before.',
                'option_d' => 'I see that movie yesterday.',
                'correct_answer' => 'C',
                'explanation' => 'Present perfect is used for actions that happened at an unspecified time before now.',
                'difficulty_level' => 'medium',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('questions')->insert($questions);
    }
} 